# Generated by Django 3.1.14 on 2023-04-27 10:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='summury',
            new_name='summary',
        ),
    ]
